Store/Store/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Entities;
using Store.Models;

namespace Store.Controllers
{
    public class CartController : Controller
    {
        StoreContext context = new StoreContext();
        public IActionResult AddCart(Cart cart)
        {
            List<Cart> cart3 = context.Cart.ToList();
            ViewData["Carts"] = cart3;
            Cart cart2 = context.Cart.FirstOrDefault(x => x.cust_id == cart.cust_id && x.prod_id == cart.prod_id);
            if (cart2 == null) 
            {
                Product product = context.Product.FirstOrDefault(x => x.Id == cart.prod_id);
                if (product.Quantity >= cart.Quantity)
                {
                    context.Cart.Add(cart);
                    context.SaveChanges();
                    List<Cart> carts = context.Cart.ToList();
                    ViewData["Carts"] = carts;
                    return View("Details", product);
                }
                else
                {
                    ViewData["Error"] = "This is not vaild Quantity";
                    return View("Details",product);
                }
            }
            else
            {
                cart2.Quantity = cart.Quantity + cart2.Quantity;
                Product product = context.Product.FirstOrDefault(x => x.Id == cart2.prod_id);
                if(product.Quantity >= cart.Quantity)
                {
                    context.Cart.Update(cart2); 
                    context.SaveChanges();
                    List<Cart> carts = context.Cart.ToList();
                    ViewData["Carts"] = carts;
                    return View("Details",product);
                }
                else
                {
                    ViewData["Error"] = "This is not vaild Quantity";
                    return View("Details",product);
                }
            }
        }

        public IActionResult CartView(int id) 
        {
            if(HttpContext.Session.GetString("Name") != null) 
            {
                List<Cart> cart = context.Cart.Where(x => x.cust_id == id).ToList();
                ViewData["Products"] = context.Product.ToList();
                return View(cart);
            }
            else
            {
                return View("SignInCustomer");
            }
        }

        public IActionResult Update(Cart cart) 
        {
            context.Cart.Update(cart);
            context.SaveChanges();
            int? id = HttpContext.Session.GetInt32("ID");
            List<Cart> cart1 = context.Cart.Where(x => x.cust_id == id).ToList();
            ViewData["Products"] = context.Product.ToList();
            return View("CartView",cart1);
        }

        public IActionResult Delete(int id) 
        {
            Cart cart = context.Cart.FirstOrDefault(x => x.Id==id);
            context.Cart.Remove(cart);
            context.SaveChanges();
            int? id1 = HttpContext.Session.GetInt32("ID");
            List<Cart> cart1 = context.Cart.Where(x => x.cust_id == id1).ToList();
            ViewData["Products"] = context.Product.ToList();
            return View("CartView", cart1);
        }

        public IActionResult ConfermCart(int id)
        {
            List<Cart> cart = context.Cart.Where(x => x.cust_id == id).ToList();
            List<ConfermCart> confermCarts = cart.Select(c => new ConfermCart
            {
                cust_id = c.cust_id,
                prod_id = c.prod_id,
                Quantity = c.Quantity,
                TotalPrice = CalculateTotalPrice(c.prod_id, c.Quantity),
                PurchaseDate = DateTime.Now
            }).ToList();

            context.ConfermCart.AddRange(confermCarts);
            context.Cart.RemoveRange(cart);
            context.SaveChanges();

            int? id1 = HttpContext.Session.GetInt32("ID");
            List<Cart> cart1 = context.Cart.Where(x => x.cust_id == id1).ToList();
            ViewData["Products"] = context.Product.ToList();
            ViewData["Conferm"] = 1;
            return View("CartView",cart1);
        }

        private double CalculateTotalPrice(int productId, int quantity)
        {
            double productPrice = GetProductPrice(productId,quantity);
            double totalPrice = productPrice * quantity;
            return totalPrice;
        }

        private double GetProductPrice(int productId,int quantity)
        {
            Product product = context.Product.FirstOrDefault(x => x.Id == productId);
            product.Quantity -= quantity;
            context.Product.Update(product);

            double productPrice = context.Product.FirstOrDefault(x => x.Id == productId).Price;
            return productPrice;
        }

        public IActionResult History(int id) 
        {
            List<ConfermCart> confermCarts = context.ConfermCart.Where(x => x.cust_id == id).ToList();
            List<Cart> carts = context.Cart.Where(x => x.cust_id == id).ToList();
            List<Product> products = context.Product.ToList();
            ViewData["Carts"] = carts;
            ViewData["Products"] = products;
            return View(confermCarts);
        }
    }
}

Store/Store/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Store.Entities;
using Store.Models;

namespace Store.Controllers
{
    public class ProductController : Controller
    {
        StoreContext context = new StoreContext();
        private IWebHostEnvironment env;

        public ProductController(IWebHostEnvironment webHostEnvironment)
        {
            env = webHostEnvironment;
        }

        public IActionResult MyProducts(int Id)
        {
            if (HttpContext.Session.GetString("Name") != null) 
            {
                List<Product> products = context.Product.Where(x => x.sell_id == Id).ToList();
                return View(products);
            }
            else
            {
                return View("SignInCustomer");
            }
        }

        public IActionResult New(Product product) 
        {
            if (HttpContext.Session.GetString("Name") != null)
            {
                return View(product);
            }
            else
            {
                return View("SignInCustomer");
            }
        }

        public async Task<IActionResult> Save(Product product) 
        {
            if (ModelState.IsValid != true)
            {
                return View("New", product);
            }
            else
            {
                string wwwRootPath = env.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(product.ImageFile.FileName);
                string extension = Path.GetExtension(product.ImageFile.FileName);
                product.Image = fileName + DateTime.Now.ToString("yymmssff") + extension;
                string path = Path.Combine(wwwRootPath + "/Image" , product.Image);
                using(var filestream = new FileStream(path, FileMode.Create))
                {
                    await product.ImageFile.CopyToAsync(filestream);
                }


                context.Product.Add(product);
                context.SaveChanges();

                int? Id = HttpContext.Session.GetInt32("ID");

                List<Product> products = context.Product.Where(x => x.sell_id == Id).ToList();

                return View("MyProducts",products);
            }
        }

        public IActionResult Details(int id) 
        {
            if(HttpContext.Session.GetString("Name") != null) 
            {
                List<Cart> cart = context.Cart.ToList();
                ViewData["Carts"] = cart;
                Product product = context.Product.FirstOrDefault(x => x.Id == id);
                return View(product);
            }
            else
            {
                return View("SignInCustomer");
            }
        }

        public IActionResult Edit(int id) 
        {
            if(HttpContext.Session.GetString("Name") != null)
            {
                Product product = context.Product.FirstOrDefault(x => x.Id == id);
                return View(product);
            }
            else
            {
                return View("SignInCustomer");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Save1([Bind("Id,Name,Description,Quantity,Price,ImageFile,sell_id")] Product product) 
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = env.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(product.ImageFile.FileName);
                string extension = Path.GetExtension(product.ImageFile.FileName);
                product.Image = fileName + DateTime.Now.ToString("yymmssff") + extension;
                string path = Path.Combine(wwwRootPath + "/Image/", product.Image);
                using (var filestream = new FileStream(path, FileMode.Create))
                {
                    await product.ImageFile.CopyToAsync(filestream);
                }

                context.Product.Update(product);
                context.SaveChanges();

                int? Id = HttpContext.Session.GetInt32("ID");

                List<Product> products = context.Product.Where(x => x.sell_id == Id).ToList();

                return View("MyProducts", products);
            }
            else 
            {
                return View("Edit",product);
            }
        }

        public IActionResult Search(string searchString)
        {
            List<Cart> cart = context.Cart.ToList();
            ViewData["Carts"] = cart;
            List<Product> products = context.Product.ToList();
            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(x => x.Name.ToLower().Contains(searchString.ToLower())).ToList();
            }
            return View("HomeStore",products);
        }

        //public IActionResult Delete(int id) 
        //{
        //    Product product = context.Product.FirstOrDefault(x =>x.Id == id);
        //    context.Product.Remove(product);
        //    context.SaveChanges();
        //    return Json(true);
        //}

        public IActionResult CheckIntNegative(int Quantity)
        {
            if (Quantity >= 0)
            {
                return Json(true);
            }
            else 
            {
                return Json(false);
            }
        }

        public IActionResult CheckDoubleNegative(double Price)
        {
            if (Price > 0)
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }
        }
    }
}

Store/Store/Controllers/UserController.cs
 using Microsoft.AspNetCore.Mvc;
using Store.Entities;
using Store.Models;

namespace Store.Controllers
{
    public class UserController : Controller
    {
        StoreContext context = new StoreContext();

        private readonly IHttpContextAccessor _context;

        public UserController(IHttpContextAccessor context)
        {
            _context = context;
        }

        public IActionResult SignInCustomer(Customer customer)
        {
            return View(customer);
        }

        public IActionResult SignUpCustomer(Customer customer)
        {
            return View(customer);
        }

        public IActionResult SignInSeller(Seller seller)
        {
            return View(seller);
        }

        public IActionResult SignUpSeller(Seller seller)
        {
            return View(seller);
        }

        public IActionResult HomeStore()
        {
            List<Product> products = context.Product.ToList();
            if (HttpContext.Session.GetString("Name") != null) 
            {
                List<Cart> cart = context.Cart.ToList();
                ViewData["Carts"] = cart;
                return View(products);
            }
            else
            {
                return View("SignInCustomer");
            }
        }

        [HttpPost]
        public IActionResult RegisterCustomer(Customer customer)
        {
            if(ModelState.IsValid != true)
            {
                return View("SignUpCustomer", customer);
            }
            else
            {
                context.Customer.Add(customer);
                context.SaveChanges();
                return View("SignInCustomer");
            }
        }

        public IActionResult LogInCustomer(Customer customer)
        {
            Customer cus = context.Customer.FirstOrDefault(x => x.Email == customer.Email && x.Password == customer.Password);
            if (cus != null)
            {
                List<Product> products = context.Product.ToList();
                List<Cart> cart = context.Cart.ToList();
                ViewData["Carts"] = cart;
                HttpContext.Session.SetString("Name", cus.Name);
                HttpContext.Session.SetInt32("ID", cus.Id);
                HttpContext.Session.SetInt32("KindUser", 0);
                return View("HomeStore",products);
            }
            else
            {
                ViewData["Error"] = "email or password is not correct";
                return View("SignInCustomer");
            }
        }

        public IActionResult LogInSeller(Seller seller)
        {
            Seller sell = context.Seller.FirstOrDefault(x => x.Email == seller.Email && x.Password == seller.Password);
            if (sell != null)
            {
                List<Product> products = context.Product.ToList();
                _context.HttpContext.Session.SetString("Name", sell.Name);
                _context.HttpContext.Session.SetInt32("ID", sell.Id);
                HttpContext.Session.SetInt32("KindUser", 1);
                return View("HomeStore", products);
            }
            else
            {
                ViewData["Error"] = "email or password is not correct";
                return View("SignInSeller");
            }
        }

        [HttpPost]
        public IActionResult RegisterSeller(Seller seller)
        {
            if (ModelState.IsValid != true)
            {
                return View("SignUpSeller", seller);
            }
            else
            {
                context.Seller.Add(seller);
                context.SaveChanges();
                return View("SignInSeller");
            }
        }

        public IActionResult ConfermPassword(string ConfPassword, string Password)
        {
            if(ConfPassword == Password)
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }
        }

        public IActionResult UnqiueSellerEmail(string Email)
        {
            Seller seller = context.Seller.FirstOrDefault(s => s.Email == Email);
            if(seller == null)
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }
        }

        public IActionResult UnqiueCustomerEmail(string Email)
        {
            Customer customer = context.Customer.FirstOrDefault(s => s.Email == Email);
            if (customer == null)
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }
        }

        public IActionResult LogOut() 
        {
            HttpContext.Session.Clear();
            return View("SignInCustomer");
        }
    }
}

Store/Store/Views/Shared/Details.cshtml
@model Product
@inject IHttpContextAccessor context
@{
    ViewData["Title"] = "Details";
    List<Cart> carts = ViewBag.Carts;
    carts = carts.Where(x => x.cust_id == context.HttpContext.Session.GetInt32("ID")).ToList();
    int numbers = carts.Count;
}

@if (context.HttpContext.Session.GetInt32("KindUser") == 0)
{
    @section Header {
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <p class="navbar-brand">Welcome @context.HttpContext.Session.GetString("Name")</p>
            <a class="navbar-brand" href="#!">Dino Shop</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link" aria-current="page" href="/User/HomeStore">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="/Product/Search">Search</a></li>
                    <li class="nav-item"><a class="nav-link" href="/Cart/History/@context.HttpContext.Session.GetInt32("ID")">History</a></li>
                </ul>
                <div class="d-flex">
                    <a class="btn btn-outline-dark" href="/Cart/CartView/@context.HttpContext.Session.GetInt32("ID")">
                        <i class="bi-cart-fill me-1"></i>
                        Cart
                        <span class="badge bg-dark text-white ms-1 rounded-pill">@numbers</span>
                    </a>
                </div>
            </div>
        </div>
    </nav>
    }
}
else if (context.HttpContext.Session.GetInt32("KindUser") == 1)
{
    @section Header {
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <p class="navbar-brand">Welcome @context.HttpContext.Session.GetString("Name")</p>
            <a class="navbar-brand" href="#!">Dino Shop</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="/User/HomeStore">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="/Product/Search">Search</a></li>
                    <li class="nav-item"><a class="nav-link" href="/Product/MyProducts/@context.HttpContext.Session.GetInt32("ID")">My Products</a></li>
                </ul>
            </div>
        </div>
    </nav>
    }
}


<h1>Details</h1>

<div class="d-flex justify-content-center">
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="/Image/@Model.Image" alt="Card image cap" width="240" height="240">
        <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>
            <p class="card-text">Description: @Model.Description</p>
            <p class="card-text">Quantity: @Model.Quantity</p>
            <p class="card-text">Price: @Model.Price</p>
            @if (@context.HttpContext.Session.GetInt32("KindUser") == 1)
            {
                <a asp-action="HomeStore" asp-controller="User" class="btn btn-primary">Go Back</a>
            }
            else if (@context.HttpContext.Session.GetInt32("KindUser") == 0)
            {
                @if (Model.Quantity != 0)
                {
                    <form method="post" asp-action="AddCart" asp-controller="Cart">
                        <input name="cust_Id" value="@context.HttpContext.Session.GetInt32("ID")" hidden />
                        <span class="text-danger">@ViewData["Error"]</span>
                        <input asp-for="@Model.Quantity" name="Quantity" min="1" max="@Model.Quantity" />
                        <input asp-for="@Model.Id" name="prod_Id" hidden />
                        <button type="submit" class="btn btn-primary">Add To Cart</button>
                    </form>
                }
                else
                {
                    <button class="btn btn-secondary btn-lg disabled" aria-disabled="true">Out Of Stock</button>
                }
                <br />
                <a href="/User/HomeStore" class="btn btn-primary">Go Back</a>
            }
        </div>
    </div>
</div>

Store/Store/Views/Shared/HomeStore.cshtml
@inject IHttpContextAccessor context
@model List<Product>
@{
    ViewData["Title"] = "HomeStore";
    int numbers = 0;
    if (context.HttpContext.Session.GetInt32("KindUser") == 0)
    {
        List<Cart> carts = ViewBag.Carts;
        carts = carts.Where(x => x.cust_id == context.HttpContext.Session.GetInt32("ID")).ToList();
        numbers = carts.Count;
    }
}

@if (context.HttpContext.Session.GetInt32("KindUser") == 0)
{
    @section Header {
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <p class="navbar-brand">Welcome @context.HttpContext.Session.GetString("Name")</p>
            <a class="navbar-brand" href="#!">Dino Shop</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Home</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="History" asp-controller="Cart" asp-route-id="@context.HttpContext.Session.GetInt32("ID")">History</a></li>
                </ul>
                <div class="d-flex">
                    <a class="btn btn-outline-dark" asp-action="CartView" asp-controller="Cart" asp-route-id="@context.HttpContext.Session.GetInt32("ID")">
                        <i class="bi-cart-fill me-1"></i>
                        Cart
                        <span class="badge bg-dark text-white ms-1 rounded-pill">@numbers</span>
                    </a>
                </div>
                <div class="d-flex">
                    <a class="btn btn-outline-danger" asp-action="LogOut" asp-controller="User">
                        <i class="bi-cart-fill me-1"></i>
                        Log Out
                    </a>
                </div>
            </div>
        </div>
    </nav>
    }
}
else if (context.HttpContext.Session.GetInt32("KindUser") == 1)
{
    @section Header {
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <p class="navbar-brand">Welcome @context.HttpContext.Session.GetString("Name")</p>
            <a class="navbar-brand" href="#!">Dino Shop</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Home</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="MyProducts" asp-controller="Product" asp-route-id="@context.HttpContext.Session.GetInt32("ID")">My Products</a></li>
                </ul>
                <div class="d-flex">
                    <a class="btn btn-outline-danger" asp-action="LogOut" asp-controller="User">
                        <i class="bi-cart-fill me-1"></i>
                        Log Out
                    </a>
                </div>
            </div>
        </div>
    </nav>
    }
}

@section Search {
    <form class="form-inline my-2 my-lg-0" asp-controller="Product" asp-action="Search">
        <div class="input-group">
            <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="SearchString">
            <div class="input-group-append">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </div>
        </div>
    </form>
}

<h1>HomeStore</h1>

<div class="container">
    <div class="row row-cols-3">
        @foreach (Product p in Model)
        {
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <img src="/Image/@p.Image" class="card-img-top" alt="Card image cap" width="240" height="240">
                    <div class="card-body">
                        <h5 class="card-title">@p.Name</h5>
                        <p class="card-text">Price: @p.Price</p>
                        <a href="/Product/Details/@p.Id" class="btn btn-primary">Details</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Store/Store/Views/Shared/SignInCustomer.cshtml
@model Customer
@{
    ViewData["Title"] = "SignInCustomer";
}

<br />

<div class="d-flex justify-content-center">
    <div style="width:50rem;background-color:lightgray;border-radius: 25px 25px; box-shadow:2px 2px;">
        <ul class="nav nav-pills nav-justified mb-3" id="ex2" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" id="tab-login" data-mdb-toggle="pill" href="#" role="tab"
                   aria-controls="pills-login">Customer</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="tab-register" data-mdb-toggle="pill" asp-action="SignInSeller" asp-controller="User" role="tab"
                   aria-controls="pills-register">Seller</a>
            </li>
        </ul>

        <ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" id="tab-login" data-mdb-toggle="pill" href="#" role="tab"
                   aria-controls="pills-login">Login</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="tab-register" data-mdb-toggle="pill" asp-action="SignUpCustomer" asp-controller="User" role="tab"
                   aria-controls="pills-register">Register</a>
            </li>
        </ul>

        <span class="text-danger">@ViewData["Error"]</span>

        <form method="get" asp-action="LogInCustomer" asp-controller="User">
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" placeholder="Email" />
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" placeholder="Password" type="password" />
            </div>
            <br />
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary">Log In</button>
            </div>
        </form>
    </div>
</div>
<br />

Store/Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] -Shop</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/css/styles.css" rel="stylesheet" />
</head>
<body>
    @RenderSection("Header",false)
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Dino Shop</h1>
                <p class="lead fw-normal text-white-50 mb-0">Welcome To Dino Shop</p>
            </div>
            <br />
            @RenderSection("Search",false);
        </div>
    </header>
    <main>
        @RenderBody()
    </main>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="/js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    @RenderSection("Scripts",false)
</body>
</html>